import Head from "next/head";
import { Footer, SideBar } from "..";
import { Provider } from "react-redux";
import { store } from "../../../store";

const layout = ({ children, title }) => {
  return (
    <Provider store={store}>
      <Head>
        <title>{title}</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className="flex items-start justify-start overflow-hidden bg-white">
        {title !== "Online Courses" && title !== "404" && <SideBar />}
        <div className="relative w-full">
          {children}
          {title !== "404" && title !== "Dashboard" && <Footer />}
        </div>
      </div>
    </Provider>
  );
};

export default layout;
