import Head from "next/head";
import { Footer, SideBar } from "..";

const layout = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className="overflow-hidden bg-white">
        <div className="flex items-start justify-start">
          {title !== "Online Courses" && <SideBar />}
          <div className="flex-1">{children}</div>
        </div>
        {title !== "404" && title !== "Dashboard" && <Footer />}
      </div>
    </>
  );
};

export default layout;
